### ISSUE TITLE
Version one ahk?

### ISSUE THREAD

**Issue by CoderGuyTedd** [teknixstuff/screenpaper#4]
When i run the ahk script is ask's me to install version one because it "needs it", 
![image](https://github.com/teknixstuff/screenpaper/assets/169071142/0bf2beb9-356c-4b1d-9a4c-d82fe6df7adc)
could we adapt it for other versions?

**Comment by teknixstuff** [comment]
I write code for AHK v1.1. I do not like v2.

**Comment by CoderGuyTedd** [comment]
Is there a way to convert it

**Comment by CoderGuyTedd** [comment]
i asked chatgpt it gave me this, I'm trying it
#NoTrayIcon
if WinExist("ahk_class Progman", "FolderView") {
    SendMessage(0x052C)
}
hWorkerW := WinExist("ahk_class WorkerW", "FolderView")
hWallpaper := DllCall("User32\FindWindowEx", "Ptr", 0, "Ptr", hWorkerW, "Str", "WorkerW", "Ptr", 0, "Ptr")
Run(TextReplace("%1%", "/p", hWallpaper))
ExitApp()

**Comment by CoderGuyTedd** [comment]
it didnt work
